version: '3.8'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: memorianexus
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ../migration:/migration
    networks:
      - memorianexus-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - memorianexus-net

networks:
  memorianexus-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local