// Package integration provides integration tests for API endpoints.
//
// This file was generated by setup_project.sh script.
package integration

// TODO: Implement integration tests for API endpoints.
