// Package memcurve provides Ebbinghaus forgetting curve calculations.
//
// This file was generated by setup_project.sh script.
package memcurve

// TODO: Implement Ebbinghaus forgetting curve calculations.
