// Package interfaces provides port definitions for internal and external communication.
//
// This file was generated by setup_project.sh script.
package interfaces

// TODO: Implement port definitions for internal and external communication.
