// Package doc Code generated by swaggo/swag. DO NOT EDIT
package doc

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/books": {
            "get": {
                "description": "Get a paginated list of books for the user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get list of books with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved list of books",
                        "schema": {
                            "$ref": "#/definitions/book.RespBooks"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new book and optionally associates tags with it",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a book",
                "parameters": [
                    {
                        "description": "Book creation data",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RespBookCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created book",
                        "schema": {
                            "$ref": "#/definitions/book.RespBook"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/books/{id}": {
            "get": {
                "description": "Get detailed information about a book.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get a book by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved book",
                        "schema": {
                            "$ref": "#/definitions/book.RespBook"
                        }
                    }
                }
            },
            "put": {
                "description": "Update information for an existing book.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update book information",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Book update data",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/book.ReqCreateBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated book",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a book from the system by ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete a book",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted book",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dungeon/campaigns/{id}/monsters": {
            "get": {
                "description": "获取复习计划的所有Monsters",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all the monsters of a specific campaign dungeon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sort by field (familiarity, difficulty, importance)",
                        "name": "sort_by",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit for pagination",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RespMonsterList"
                        }
                    },
                    "404": {
                        "description": "Dungeon not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dungeon/campaigns/{id}/next_monsters": {
            "get": {
                "description": "获取复习计划的后n个Monsters",
                "produces": [
                    "application/json"
                ],
                "summary": "Get the next n monsters of a specific dungeon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of monsters to fetch",
                        "name": "count",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sort by field (familiarity, difficulty, importance)",
                        "name": "sort_by",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RespMonsterList"
                        }
                    },
                    "404": {
                        "description": "Dungeon not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dungeon/campaigns/{id}/report_result": {
            "post": {
                "description": "上报复习计划的Monster结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Report the result of a specific monster",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UserMonster result data",
                        "name": "result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dungeon.ReqReportMonsterResult"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Dungeon or UserMonster not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dungeon/campaigns/{id}/results": {
            "get": {
                "description": "获取复习计划的结果",
                "produces": [
                    "application/json"
                ],
                "summary": "Get the results of a specific dungeon",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dungeon.RespCampaignResult"
                        }
                    },
                    "404": {
                        "description": "Dungeon not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dungeon/dungeons": {
            "get": {
                "description": "获取复习计划列表",
                "produces": [
                    "application/json"
                ],
                "summary": "Get the list of dungeon campaigns",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.RespDungeonList"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的复习计划",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a new dungeon campaign",
                "parameters": [
                    {
                        "description": "Dungeon campaign data",
                        "name": "campaign",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dungeon.ReqCreateDungeon"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.RespDungeon"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dungeon/dungeons/{id}": {
            "get": {
                "description": "获取复习计划详情",
                "produces": [
                    "application/json"
                ],
                "summary": "Get the details of a specific dungeon campaign",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "the dungeon with its associations",
                        "schema": {
                            "$ref": "#/definitions/dto.RespDungeon"
                        }
                    },
                    "404": {
                        "description": "Dungeon not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "更新复习计划",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a specific dungeon campaign",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dungeon campaign data",
                        "name": "campaign",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dungeon.ReqUpdateDungeon"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updater",
                        "schema": {
                            "$ref": "#/definitions/dto.RespDungeon"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Dungeon not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除复习计划",
                "summary": "Delete a specific dungeon campaign",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "updater",
                        "schema": {
                            "$ref": "#/definitions/dto.RespDungeon"
                        }
                    },
                    "404": {
                        "description": "Dungeon not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dungeon/dungeons/{id}/books": {
            "get": {
                "description": "获取复习计划的 Books",
                "produces": [
                    "application/json"
                ],
                "summary": "Get the books of a specific dungeon",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "404": {
                        "description": "Dungeon not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "向现有复习计划添加书籍",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Add books to an existing dungeon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Books to add",
                        "name": "books",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dungeon.ReqAddDungeonBooks"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RespDungeon"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除复习计划的 Books",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Remove books from a specific dungeon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dungeon books data",
                        "name": "books",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dungeon.ReqRemoveDungeonBooks"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Dungeon or Book not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dungeon/dungeons/{id}/items": {
            "get": {
                "description": "获取复习计划的 Items",
                "produces": [
                    "application/json"
                ],
                "summary": "Get the items of a specific dungeon",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "404": {
                        "description": "Dungeon not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "向现有复习计划添加学习材料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Add items to an existing dungeon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Items to add",
                        "name": "items",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dungeon.ReqAddDungeonItems"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RespDungeon"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除复习计划的 Items",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Remove items from a specific dungeon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dungeon items data",
                        "name": "items",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dungeon.ReqRemoveDungeonItems"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Dungeon or Item not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dungeon/dungeons/{id}/tags": {
            "get": {
                "description": "获取复习计划的 TagNames",
                "produces": [
                    "application/json"
                ],
                "summary": "Get the tags of a specific dungeon",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "404": {
                        "description": "Dungeon not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "向现有复习计划添加标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Add tags to an existing dungeon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tags to add",
                        "name": "tags",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dungeon.ReqAddDungeonTags"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RespDungeon"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除复习计划的 TagNames",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Remove tags from a specific dungeon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dungeon tags data",
                        "name": "tags",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dungeon.ReqRemoveDungeonTags"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Dungeon or Tag not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dungeon/endless/{id}/monsters": {
            "get": {
                "description": "获取复习计划的所有Monsters及其关联的 Items, Books, TagNames",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all the monsters of a specific endless dungeon with associations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dungeon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sort by field (familiarity, difficulty, importance)",
                        "name": "sort_by",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit for pagination",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RespMonsterList"
                        }
                    },
                    "404": {
                        "description": "Dungeon not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/items": {
            "get": {
                "description": "Get a list of items for the user with optional filters for book and type and support for pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get a list of items with optional filters",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "book_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Type of item",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved items",
                        "schema": {
                            "$ref": "#/definitions/dto.RespItemList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new item in the system with optional book affiliations and tags.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a new item",
                "parameters": [
                    {
                        "description": "Item creation data",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/item.ReqCreateItem"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created item with books and tags",
                        "schema": {
                            "$ref": "#/definitions/dto.RespItemCreate"
                        }
                    },
                    "400": {
                        "description": "Bad Request if too many books or tags, or bad data",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/items/{id}": {
            "get": {
                "description": "Get detailed information about an item, including its tags.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get an item by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved item with tags",
                        "schema": {
                            "$ref": "#/definitions/dto.RespItemGet"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an item's type, content, or associated tags.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update an item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Item update data",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/item.ReqUpdateItem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated item",
                        "schema": {
                            "$ref": "#/definitions/dto.RespItemUpdate"
                        }
                    },
                    "400": {
                        "description": "Bad Request with invalid item ID or update data",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error with failing to update the item",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an item from the system by ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete an item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted item",
                        "schema": {
                            "$ref": "#/definitions/dto.RespItemDelete"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves the profile information for the user who made the request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get the current user's profile",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved user profile",
                        "schema": {
                            "$ref": "#/definitions/dto.RespProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Updates the profile information for the user who made the request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "description": "User profile update info",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.ReqUpdateProfile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated user profile",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile/points": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves points information for the current user.",
                "produces": [
                    "application/json"
                ],
                "summary": "Get user points",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved user points",
                        "schema": {
                            "$ref": "#/definitions/dto.RespPoints"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile/settings/advance": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves advanced settings information for the current user.",
                "produces": [
                    "application/json"
                ],
                "summary": "Get user advanced settings",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved user advanced settings",
                        "schema": {
                            "$ref": "#/definitions/dto.RespSettingsAdvance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Updates advanced settings for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update user advanced settings",
                "parameters": [
                    {
                        "description": "User advanced settings update info",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.ReqUpdateUserSettingsAdvance"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated user advanced settings",
                        "schema": {
                            "$ref": "#/definitions/dto.RespSettingsAdvance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile/settings/memorization": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves settings information for the user who made the request.",
                "produces": [
                    "application/json"
                ],
                "summary": "Get user settings",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved user settings",
                        "schema": {
                            "$ref": "#/definitions/dto.RespSettingsMemorization"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Updates the settings for the user who made the request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update user settings",
                "parameters": [
                    {
                        "description": "User settings update info",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.ReqUpdateUserSettingsMemorization"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated user settings",
                        "schema": {
                            "$ref": "#/definitions/dto.RespSettingsMemorization"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "book.ReqCreateBook": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "book.RespBook": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "book.RespBooks": {
            "type": "object",
            "properties": {
                "books": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/book.RespBook"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                }
            }
        },
        "def.DifficultyLevel": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                17,
                18,
                19,
                33,
                34,
                35,
                49,
                50,
                51,
                65,
                66,
                67,
                68
            ],
            "x-enum-varnames": [
                "NoviceNormal",
                "NoviceAdvanced",
                "NoviceChallenge",
                "AmateurNormal",
                "AmateurAdvanced",
                "AmateurChallenge",
                "ProfessionalNormal",
                "ProfessionalAdvanced",
                "ProfessionalChallenge",
                "ExpertNormal",
                "ExpertAdvanced",
                "ExpertChallenge",
                "MasterNormal",
                "MasterAdvanced",
                "MasterChallenge",
                "MasterExtreme"
            ]
        },
        "def.DungeonType": {
            "type": "integer",
            "enum": [
                1,
                2,
                33
            ],
            "x-enum-comments": {
                "DungeonTypeCampaign": "战役地牢",
                "DungeonTypeEndless": "无尽地牢",
                "DungeonTypeInstance": "即时副本 (随机地牢)"
            },
            "x-enum-varnames": [
                "DungeonTypeCampaign",
                "DungeonTypeEndless",
                "DungeonTypeInstance"
            ]
        },
        "def.ImportanceLevel": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                17,
                18,
                19,
                20,
                33,
                34,
                35,
                36
            ],
            "x-enum-varnames": [
                "DomainGeneral",
                "DomainKey",
                "DomainEssential",
                "AreaGeneral",
                "AreaKey",
                "AreaEssential",
                "AreaMasterPiece",
                "GlobalGeneral",
                "GlobalKey",
                "GlobalEssential",
                "GlobalMasterPiece"
            ]
        },
        "dto.Book": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.Dungeon": {
            "type": "object",
            "properties": {
                "books": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rule": {
                    "type": "string"
                },
                "tag_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tag_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/def.DungeonType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.DungeonMonster": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "creator_id": {
                    "type": "integer"
                },
                "difficulty": {
                    "$ref": "#/definitions/def.DifficultyLevel"
                },
                "dungeonID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "importance": {
                    "$ref": "#/definitions/def.ImportanceLevel"
                },
                "monsterSource": {
                    "$ref": "#/definitions/model.MonsterSource"
                },
                "monsterSourceEntityID": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "visibility": {
                    "description": "显影程度，根据复习次数变化",
                    "type": "integer"
                }
            }
        },
        "dto.Item": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "creator_id": {
                    "type": "integer"
                },
                "difficulty": {
                    "$ref": "#/definitions/def.DifficultyLevel"
                },
                "id": {
                    "type": "integer"
                },
                "importance": {
                    "$ref": "#/definitions/def.ImportanceLevel"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.Points": {
            "type": "object",
            "properties": {
                "cash": {
                    "type": "integer"
                },
                "gem": {
                    "type": "integer"
                },
                "vip_score": {
                    "type": "integer"
                }
            }
        },
        "dto.Profile": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "dto.RespBookCreate": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Book"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.RespDungeon": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Dungeon"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.RespDungeonList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Dungeon"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.RespItemCreate": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Item"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.RespItemDelete": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Item"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.RespItemGet": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Item"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.RespItemList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Item"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.RespItemUpdate": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Item"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.RespMonsterList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DungeonMonster"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.RespPoints": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Points"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.RespProfile": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Profile"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.RespSettingsAdvance": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.SettingsAdvance"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.RespSettingsMemorization": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.SettingsMemorization"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.SettingsAdvance": {
            "type": "object",
            "properties": {
                "email_notifications": {
                    "type": "boolean"
                },
                "language": {
                    "type": "string"
                },
                "push_notifications": {
                    "type": "boolean"
                },
                "theme": {
                    "type": "string"
                }
            }
        },
        "dto.SettingsMemorization": {
            "type": "object",
            "properties": {
                "difficulty_preference": {
                    "type": "integer"
                },
                "quiz_mode": {
                    "type": "string"
                },
                "review_interval": {
                    "description": "Definitions should match with ProfileMemorizationSetting",
                    "type": "integer"
                }
            }
        },
        "dto.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "dungeon.ReqAddDungeonBooks": {
            "type": "object",
            "properties": {
                "books": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dungeon.ReqAddDungeonItems": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dungeon.ReqAddDungeonTags": {
            "type": "object",
            "properties": {
                "tag_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dungeon.ReqCreateDungeon": {
            "type": "object",
            "properties": {
                "books": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "description": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rule": {
                    "type": "string"
                },
                "tag_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tag_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/def.DungeonType"
                }
            }
        },
        "dungeon.ReqRemoveDungeonBooks": {
            "type": "object",
            "properties": {
                "books": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dungeon.ReqRemoveDungeonItems": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dungeon.ReqRemoveDungeonTags": {
            "type": "object",
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dungeon.ReqReportMonsterResult": {
            "type": "object",
            "properties": {
                "monster_id": {
                    "type": "integer"
                },
                "result": {
                    "description": "\"unknown\", \"familiar\", \"remembered\"",
                    "type": "string"
                }
            }
        },
        "dungeon.ReqUpdateDungeon": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "rule": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/def.DungeonType"
                }
            }
        },
        "dungeon.RespCampaignResult": {
            "type": "object",
            "properties": {
                "today_difficulty": {
                    "type": "integer"
                },
                "total_monsters": {
                    "type": "integer"
                }
            }
        },
        "item.ReqCreateItem": {
            "type": "object",
            "properties": {
                "book_ids": {
                    "description": "用于接收一个或多个 BookID",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "content": {
                    "type": "string"
                },
                "tags": {
                    "description": "新增字段，用于接收一组 Tag 名称",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "item.ReqUpdateItem": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "tags": {
                    "description": "新增字段",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.MonsterSource": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "MonsterSourceItem",
                "MonsterSourceBook",
                "MonsterSourceTag"
            ]
        },
        "profile.ReqUpdateProfile": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "profile.ReqUpdateUserSettingsAdvance": {
            "type": "object",
            "properties": {
                "email_notifications": {
                    "type": "boolean"
                },
                "language": {
                    "type": "string"
                },
                "push_notifications": {
                    "type": "boolean"
                },
                "theme": {
                    "type": "string"
                }
            }
        },
        "profile.ReqUpdateUserSettingsMemorization": {
            "type": "object",
            "properties": {
                "difficulty_preference": {
                    "type": "integer"
                },
                "quiz_mode": {
                    "type": "string"
                },
                "review_interval": {
                    "type": "integer"
                }
            }
        },
        "utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
